from . import res_users
from . import digii_slide_channel
from . import digii_slide_channel_tag
from . import digii_course_category
from . import digii_slide_channel_partner
from . import digii_slide_slide
from . import digii_slide_slide_resource
from . import blog
from . import forum
from . import digii_class
from . import survey_survey_course
#from . import digii_exam_attempt
#from . import digii_exam_certificate
#from . import survey_question
#from . import survey_user_input
#from . import survey_user_input_line
