{
    'name': 'LMS - Learning Management System',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Système de gestion de l\'apprentissage type Moodle',
    'author': 'Ben Slimen Louay',

    'depends': [
        'website',
        'website_slides',
        'mail',
        'base',
        'web',
        'portal',
        'website_blog',
        'website_forum',
        'survey',
        'digii_exam_manager',
    ],
    'data': [
        'security/lms_groups.xml',
        'security/ir.model.access.csv',
        'data/lms_config.xml',
        'views/digii_course_category_views.xml',
        'views/digii_slide_channel_views.xml',
        'views/digii_class_views.xml',
        'views/forum_views.xml',
        'views/blog_views.xml',
        'views/digii_slide_channel_tag_views.xml',
        'views/digii_slide_channel_partner_views.xml',
        'views/digii_slide_slide_views.xml',
        'views/lms_users_views.xml',
        'views/survey_exam_course_views.xml',
        'views/website_templates.xml',
        'templates/home.xml',
        'templates/slides_courses.xml',
        'views/portal_exam_filter_templates.xml',
        'views/digii_menu_views.xml',
        'views/lms_menu_access.xml',
    ],    'assets': {
    'web.assets_backend': [
        'digii_lms/static/src/scss/digii_dashboard.css',
        'digii_lms/static/src/xml/digii_dashboard.xml',
        'digii_lms/static/src/js/digii_dashboard.js',
        'digii_lms/static/src/css/exam_dashboard.css',
        'digii_lms/static/src/xml/exam_dashboard.xml',
        'digii_lms/static/src/js/exam_dashboard.js',
    ],
        'web.assets_frontend': [
            'digii_lms/static/src/css/lms_styles.css',
            'digii_lms/static/src/css/lms_home.css',
            'digii_lms/static/src/css/lms_slides.css',
            'digii_lms/static/src/css/lms_coherence.css',
            'digii_lms/static/src/js/lms_main.js',
        ],
    },

    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}